envName="dev"

[dev]
buildDir = "${HOME}/.easifem/easifem/build/"
installDir= "${HOME}/.easifem/easifem/install/"
sourceDir= "${HOME}/.easifem/easifem/src/"
lintDir= "${HOME}/.easifem/easifem/lint/"
buildType = "Debug" # "Release", "Both"
buildSharedLibs = true
buildStaticLibs = false
buildSystem = "cmake"

